name: Download release asset (artifact)
description: Download and extract an asset/artifact associated with given release
author: ChristopheRivier
branding:
  icon: download
  color: green
inputs:
  release_name:
    description: Release Name
    required: true
  asset_name:
    description: Name of the asset (artifact)
    required: false
  repo:
    description: Repository name with owner (like actions/checkout)
    required: true
  dest_path:
    description: Where to unpack the asset
    required: false
    default: "./"
  token:
    description: GitHub token
    required: false
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/script.sh
      env: 
        release_name: ${{ github.event.inputs.release_name }}
        asset_name: ${{ github.event.inputs.asset_name }}
        repo: ${{ github.event.inputs.repo }}
        dest_path: ${{ github.event.inputs.dest_path }}
        token: ${{ github.event.inputs.token }}
      shell: bash