# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: Release Name
        required: true
      asset_name:
        description: Name of the asset (artifact)
        required: false
      repo:
        description: Repository name with owner (like actions/checkout)
        required: false
        default: ${{github.repository}}
      dest_path:
        description: Where to unpack the asset
        required: false
        default: "./"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: test actions
        uses: Marau78/download-release-asset@v1
        with:
          # Optional, GitHub token mandatory for private repo
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Mandatory, release tag name
          release_name: ${{github.events.inputs.release_name}}
          # Optional, uploaded asset name,
          # will download all assets if not specified
          # and extract them if end by .zip.
          asset_name: ${{github.events.inputs.asset_name}}
          # Optional, directory where to extract artifact
          dest_path: ${{github.events.inputs.asset_name}}
          # Optional, defaults to current repo
          repo: ${{github.events.inputs.repo}}

